# Generated by Django 5.1.4 on 2024-12-12 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='comments',
            new_name='foods',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='mileage',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must be greater than 1 character')]),
        ),
    ]
